### ISSUE TITLE
[Bug]: icon will overlap with the close button

### ISSUE THREAD

**Issue by hanaexcl** [199ocero/activity-timeline#11]
### What happened?

It'll overlap with the close button.

![螢幕擷取畫面 2024-01-19 031042](https://github.com/199ocero/activity-timeline/assets/22741314/907ce493-3500-4d34-a4b4-2f4c3513abc2)

### How to reproduce the bug

Using ViewAction in slideOver mode.

```php
Tables\Actions\ViewAction::make()->slideOver(),
```

### Package Version

1.2

### PHP Version

8.2

### Laravel Version

10.41

### Notes

Removing z-10 may solve this issue, but it's uncertain whether it will cause other problems.

```html
activity-icon.blade.php

<div class="relative z-10 w-8 h-8 flex justify-center items-center">
to
<div class="relative w-8 h-8 flex justify-center items-center">
```

**Comment by 199ocero** [comment]
Thank you for this @hanaexcl ! I will not remove the z-10 but maybe add a scrollable for this. Will be fix for next release.

**Comment by 199ocero** [comment]
Hi @hanaexcl , I go to your fix and I tested if there are any breaking change to layout but seems that there is not. I've added a new release with this fix. Thank youu!

**Comment by hanaexcl** [comment]
> Hi @hanaexcl , I go to your fix and I tested if there are any breaking change to layout but seems that there is not. I've added a new release with this fix. Thank youu!

Thank you, it works!
