### ISSUE TITLE
[Enhancement]: Adding support for Spatie Activity Log

### ISSUE THREAD

**Issue by 199ocero** [199ocero/activity-timeline#3]
### What happened?

Currently the only supported to use this package is via making an infolists builder.

### How to reproduce the bug

.

### Package Version

1.0.1

### PHP Version

8.1

### Laravel Version

10.0.0

### Which operating systems does with happen with?

macOS

### Notes

I want to support making a custom page to show all activity logs from spatie package from a specific record/model.

**Comment by aeq-dev** [comment]
Yes please :)))) :heart:
